# Generated by Django 6.0.3 on 2026-03-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0002_task_assignee_task_reviewers_alter_board_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='Niedrig', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'to do'), ('in_progress', 'in progress'), ('review', 'review')], default='Nicht_Begonnen', max_length=15),
        ),
    ]
