# Generated by Django 6.0.3 on 2026-03-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0004_task_comments_count_task_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'to do'), ('progress', 'progress'), ('review', 'review')], default='to_do', max_length=15),
        ),
    ]
