# Generated by Django 6.0.3 on 2026-03-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'to do'), ('in_progress', 'in progress'), ('review', 'review')], default='to_do', max_length=15),
        ),
    ]
