# Generated by Django 6.0.3 on 2026-03-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to-do', 'to do'), ('in-progress', 'in progress'), ('review', 'review')], default='to_do', max_length=15),
        ),
    ]
