# Generated by Django 6.0.3 on 2026-03-31 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0008_alter_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='done_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to-do', 'to do'), ('in-progress', 'in progress'), ('done', 'done')], default='to-do', max_length=15),
        ),
    ]
