# Generated by Django 6.0.3 on 2026-04-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0009_alter_task_reviewers_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to-do', 'to do'), ('in-progress', 'in progress'), ('review', 'review'), ('done', 'done')], default='to-do', max_length=15),
        ),
    ]
